name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: glady-andrews-main

      - name: Build project
        run: npm run build
        working-directory: glady-andrews-main

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: glady-andrews-main/dist
          branch: gh-pages
          clean: true
          token: ${{ secrets.GH_PAT }}
